# cicd workflow for running tests with pytest
# needs to first install pdm, then install torch cpu manually and then install the package
# then run the tests

name: tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: "cirun-cpu-runner-${{ github.run_id }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pdm
        run: |
          python -m pip install pdm
          pdm --version

      - name: Install torch
        run: |
          python -m pip install torch==1.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html

      - name: Install package (including dev dependencies)
        run: |
          pdm install
          pdm install --dev

      - name: Run tests
        run: |
          pdm run pytest --nbval-lax
