name: linting

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  linting:
    name: "pre-commit hooks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1
